-- VHDL Entity Multiplexer_lib.Mutliplexer81.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:41:41 03-03-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Mutliplexer81 IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      Y  : OUT    std_logic
   );

-- Declarations

END Mutliplexer81 ;

--
-- VHDL Architecture Multiplexer_lib.Mutliplexer81.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:41:41 03-03-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF Mutliplexer81 IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(S0, S1, S2)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (S0 = '0') AND (S1 = '0') AND (S2 = '0') THEN
         Y <= '0';
      ELSIF (S0 = '0') AND (S1 = '0') AND (S2 = '1') THEN
         Y <= '1';
      ELSIF (S0 = '0') AND (S1 = '1') AND (S2 = '0') THEN
         Y <= '1';
      ELSIF (S0 = '0') AND (S1 = '1') AND (S2 = '1') THEN
         Y <= '0';
      ELSIF (S0 = '1') AND (S1 = '0') AND (S2 = '0') THEN
         Y <= '0';
      ELSIF (S0 = '1') AND (S1 = '0') AND (S2 = '1') THEN
         Y <= '0';
      ELSIF (S0 = '1') AND (S1 = '1') AND (S2 = '0') THEN
         Y <= '1';
      ELSIF (S0 = '1') AND (S1 = '1') AND (S2 = '1') THEN
         Y <= '1';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
