-- VHDL Entity FlipFlop_T_lib.T_flip_flop.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:41:17 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY T_flip_flop IS
   PORT( 
      Q    : IN     std_logic;
      T    : IN     std_logic;
      Qout : OUT    std_logic
   );

-- Declarations

END T_flip_flop ;

--
-- VHDL Architecture FlipFlop_T_lib.T_flip_flop.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:41:17 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF T_flip_flop IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(Q, T)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (T = '0') AND (Q = '0') THEN
         Qout <= '0';
      ELSIF (T = '0') AND (Q = '1') THEN
         Qout <= '1';
      ELSIF (T = '1') AND (Q = '0') THEN
         Qout <= '1';
      ELSIF (T = '1') AND (Q = '1') THEN
         Qout <= '0';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
