/*append is a library function of prolog*/
last1(L,X):-append(L1,[X],L).
/*i.e. it will check if L is generated by appending X to last of L1 */
/*if so, then the inbuild function append will return true. Thus, last1(L,X) will return true*/
/*if the inbulid function append will return false. Then last1(L,X) will return false*/
/*
?- last([1],X).
X = 1.

?- last([1,2],X).
X = 2.

?- last([],X).
false.

?- last([1,2,3],X).
X = 3.
*/
