-- VHDL Entity Flip_Flop_JK_lib.JK_Flip.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 09:42:44 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY JK_Flip IS
   PORT( 
      J    : IN     std_logic;
      K    : IN     std_logic;
      Q    : IN     std_logic;
      Qout : OUT    std_logic
   );

-- Declarations

END JK_Flip ;

--
-- VHDL Architecture Flip_Flop_JK_lib.JK_Flip.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 09:42:44 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF JK_Flip IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(J, K, Q)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (J = '0') AND (K = '0') AND (Q = '0') THEN
         Qout <= '0';
      ELSIF (J = '0') AND (K = '0') AND (Q = '1') THEN
         Qout <= '1';
      ELSIF (J = '0') AND (K = '1') AND (Q = '0') THEN
         Qout <= '0';
      ELSIF (J = '0') AND (K = '1') AND (Q = '1') THEN
         Qout <= '0';
      ELSIF (J = '1') AND (K = '0') AND (Q = '0') THEN
         Qout <= '1';
      ELSIF (J = '1') AND (K = '0') AND (Q = '1') THEN
         Qout <= '1';
      ELSIF (J = '1') AND (K = '1') AND (Q = '0') THEN
         Qout <= '1';
      ELSIF (J = '1') AND (K = '1') AND (Q = '1') THEN
         Qout <= '0';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
