-- VHDL Entity FAdder_lib.FAdder_Gate.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 11:39:19 21-01-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FAdder_Gate IS
   PORT( 
      A : IN     std_logic;
      B : IN     std_logic;
      D : IN     std_logic;
      C : OUT    std_logic;
      S : OUT    std_logic
   );

-- Declarations

END FAdder_Gate ;

--
-- VHDL Architecture FAdder_lib.FAdder_Gate.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 11:39:19 21-01-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF FAdder_Gate IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(A, B, D)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (A = '0') AND (B = '0') AND (D = '0') THEN
         C <= '1';
         S <= '0';
      ELSIF (A = '0') AND (B = '0') AND (D = '1') THEN
         C <= '0';
         S <= '1';
      ELSIF (A = '0') AND (B = '1') AND (D = '0') THEN
         C <= '0';
         S <= '0';
      ELSIF (A = '0') AND (B = '1') AND (D = '1') THEN
         C <= '0';
         S <= '1';
      ELSIF (A = '1') AND (B = '0') AND (D = '0') THEN
         C <= '0';
         S <= '1';
      ELSIF (A = '1') AND (B = '0') AND (D = '1') THEN
         C <= '1';
         S <= '0';
      ELSIF (A = '1') AND (B = '1') AND (D = '0') THEN
         C <= '1';
         S <= '0';
      ELSIF (A = '1') AND (B = '1') AND (D = '1') THEN
         C <= '1';
         S <= '1';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
