-- VHDL Entity Flip_Flop_D_lib.D_FlipFlop.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:33:39 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY D_FlipFlop IS
   PORT( 
      D    : IN     std_logic;
      Q    : IN     std_logic;
      Qout : OUT    std_logic
   );

-- Declarations

END D_FlipFlop ;

--
-- VHDL Architecture Flip_Flop_D_lib.D_FlipFlop.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:33:39 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF D_FlipFlop IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(D, Q)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (D = '0') AND (Q = 'X') THEN
         Qout <= '0';
      ELSIF (D = '1') AND (Q = 'X') THEN
         Qout <= '1';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
