-- VHDL Entity Flip_Flop_SR_lib.SR_FlipFlop.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:00:36 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY SR_FlipFlop IS
   PORT( 
      Q    : IN     std_logic;
      R    : IN     std_logic;
      S    : IN     std_logic;
      Qout : OUT    std_logic
   );

-- Declarations

END SR_FlipFlop ;

--
-- VHDL Architecture Flip_Flop_SR_lib.SR_FlipFlop.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 10:00:36 11-02-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF SR_FlipFlop IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(Q, R, S)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (Q = '0') AND (R = '0') AND (S = '0') THEN
         Qout <= '0';
      ELSIF (Q = '1') AND (R = '0') AND (S = '0') THEN
         Qout <= '1';
      ELSIF (Q = '0') AND (R = '1') AND (S = '0') THEN
         Qout <= '0';
      ELSIF (Q = '1') AND (R = '1') AND (S = '0') THEN
         Qout <= '0';
      ELSIF (Q = '0') AND (R = '0') AND (S = '1') THEN
         Qout <= '1';
      ELSIF (Q = '1') AND (R = '0') AND (S = '1') THEN
         Qout <= '1';
      ELSIF (Q = '0') AND (R = '1') AND (S = '1') THEN
         Qout <= 'X';
      ELSIF (Q = '1') AND (R = '1') AND (S = '1') THEN
         Qout <= 'X';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
