-- VHDL Entity NOT_gate_lib.NOT_gate.symbol
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 11:12:00 21-01-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY NOT_gate IS
   PORT( 
      A : IN     std_logic;
      B : IN     std_logic;
      C : OUT    std_logic
   );

-- Declarations

END NOT_gate ;

--
-- VHDL Architecture NOT_gate_lib.NOT_gate.tbl
--
-- Created:
--          by - cst.UNKNOWN (EC3)
--          at - 11:12:00 21-01-2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF NOT_gate IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(A, B)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (A = '0') AND (B = '0') THEN
         C <= '1';
      ELSIF (A = '0') AND (B = '1') THEN
         C <= '0';
      ELSIF (A = '1') AND (B = '0') THEN
         C <= '0';
      ELSIF (A = '1') AND (B = '1') THEN
         C <= '1';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
